### PR TITLE
Fix crafttweaker compability

### PR DESCRIPTION
**Pull request by ThaCheeseBun**
Fix for the problem described in #3. Have tested my own .jar on a server with 200 mods successfully for 2 weeks so should work fine.

### CODE REVIEW

**Comment by Salandora** [comment]
I have this fixed in 1777e4e already but haven't pushed it to 1.20.1 yet.

**Comment by ThaCheeseBun** [comment]
ah i see, push it whenever possible then

**Comment by VorpBloxxer** [comment]
they forgor to push on 1.20.1

**Comment by Salandora** [comment]
No fix is in the feature-update branch which will get merged into the fabric-dev branch once it's confirmed stable ;)
https://github.com/Salandora/SophisticatedCore/commit/5da0894aad82dd4f70308d57baeeb66a1e3a7e61

**Comment by VorpBloxxer** [comment]
oh! thank you for the info

**Pull request closed without merging**
